packages:
  - packages/*
  - samples/*
  - tools/*
  - website

catalog:
  "@changesets/cli": 2.29.8
  "@commitlint/cli": 20.2.0
  "@commitlint/config-conventional": 20.2.0
  "@standard-schema/spec": 1.0.0
  "@swan-io/boxed": 3.2.1
  "@temporalio/client": 1.13.2
  "@temporalio/worker": 1.13.2
  "@temporalio/workflow": 1.13.2
  "@types/node": 25.0.1
  "@vitest/coverage-v8": 4.0.15
  arktype: 2.1.28
  knip: 5.73.4
  lefthook: 2.0.11
  oxfmt: 0.17.0
  oxlint: 1.32.0
  pino: 10.1.0
  pino-pretty: 13.1.3
  sort-package-json: 3.5.1
  testcontainers: 11.10.0
  ts-pattern: 5.5.0
  tsdown: 0.17.3
  tsx: 4.21.0
  turbo: 2.6.3
  typescript: 5.9.3
  valibot: 1.2.0
  vitest: 4.0.15
  zod: 4.1.13
