packages:
  - packages/*
  - samples/*
  - tools/*

catalog:
  "@changesets/cli": 2.29.8
  "@changesets/config": 3.1.2
  "@swan-io/boxed": 3.2.1
  "@temporalio/client": 1.13.2
  "@temporalio/worker": 1.13.2
  "@temporalio/workflow": 1.13.2
  "@types/node": 24.10.2
  "@vitest/coverage-v8": 4.0.15
  knip: 5.73.1
  lefthook: 2.0.9
  oxfmt: 0.17.0
  oxlint: 1.32.0
  pino: 10.1.0
  pino-pretty: 13.1.3
  testcontainers: 11.10.0
  ts-node: 10.9.2
  ts-pattern: 5.9.0
  tsdown: 0.17.2
  tsx: 4.21.0
  turbo: 2.6.3
  type-fest: 5.3.1
  typescript: 5.9.3
  vitest: 4.0.15
  zod: 4.1.13
